export enum SocketEvent {
    USER_START_GAME = 'USER_START_GAME',
    USER_MOVE = 'USER_MOVE',
    USER_ATTACK = 'USER_ATTACK',
    USER_END_TURN = 'USER_END_TURN',
    USER_JOIN_MAP = 'USER_JOIN_MAP',
 }